services:
  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - mongo_data:/data/db
    networks:
      - areo_networks

  api:
    build:
      context: ./backend
    restart: always
    ports:
      - ${API_PORT}:${API_PORT}
    environment:
      MONGO_URI: ${MONGO_URI}
      MONGO_DB_NAME: ${MONGO_DB_NAME}
      JWT_SECRET: ${JWT_SECRET}
      HASH_SECRET: ${HASH_SECRET}
      API_HOST: ${API_HOST}
      API_PORT: ${API_PORT}
      JWT_ALGO: ${JWT_ALGO}
    depends_on:
      - mongo
    volumes:
      - ./backend:/app
    networks:
      - areo_networks
  app:
    build:
      context: ./frontend
    restart: always
    ports:
      - ${APP_PORT}:${APP_PORT}
    depends_on:
      - api
    volumes:
      - ./frontend:/app
    networks:
      - areo_networks

volumes:
  mongo_data:


networks:
  areo_networks:
    driver: bridge
